version: "3.0"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - back-net
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL:-mongodb://mongodb:27017/?compressors=zlib&gssapiServiceName=mongodb}
      - DB_NAME=${DB_NAME:-a11ywatch}
      - APOLLO_KEY=${APOLLO_KEY}
      - APOLLO_GRAPH_VARIANT=${APOLLO_GRAPH_VARIANT:-current}
      - APOLLO_SCHEMA_REPORTING=${APOLLO_SCHEMA_REPORTING:-true}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
      - WATCHER_CLIENT_URL=${WATCHER_CLIENT_URL:-http://crawler:8000}
      - GRAPHQL_PORT=${GRAPHQL_PORT:-8080}
      - EMAIL_SERVICE_URL=${EMAIL_SERVICE_URL}
      - EMAIL_MAIN_LEAD=${EMAIL_MAIN_LEAD}
      - EMAIL_SERVICE_PASSWORD=${EMAIL_SERVICE_PASSWORD:-SomePassword}
      - EMAIL_CLIENT_ID=${EMAIL_CLIENT_ID}
      - EMAIL_CLIENT_KEY=${EMAIL_CLIENT_KEY}
      - STRIPE_KEY=${STRIPE_KEY}
      - SCRIPTS_CDN_URL=${SCRIPTS_CDN_URL:-http://localhost:8090/api}
      - PUPPET_SERVICE=${PUPPET_SERVICE:-http://pagemind:8040}
      - ROOT_URL=${ROOT_URL:-http://localhost:8080}
      - STRIPE_BASIC_PLAN=${STRIPE_BASIC_PLAN}
      - STRIPE_PREMIUM_PLAN=${STRIPE_PREMIUM_PLAN}
      - MAV_CLIENT_URL=${MAV_CLIENT_URL:-http://mav:8020}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - LOGGER_ENABLED=${LOGGER_ENABLED:-true}
      - LOGGER_URL=${LOGGER_URL:-logger}
      - ADMIN_ORIGIN=${ADMIN_ORIGIN}
      - BACKGROUND_CRAWL=${BACKGROUND_CRAWL:-true}
      - DOCKER_ENV=true
      - REDIS_CLIENT=${REDIS_CLIENT:-redis://redis:6379}
  redis:
    container_name: redis
    image: bitnami/redis:6.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - back-net
networks:
  back-net:
